In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
## sentences
sent = [ " the glass of milk",
       "the glass of juice",
       "the cup of tea",
       "I am a good boy",
       "I am a good developer",
       " understanding the meaning of words",
       "your videos are good"]

In [13]:
sent

[' the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 ' understanding the meaning of words',
 'your videos are good']

In [14]:
## Vocabulary size
voc_size = 10000

In [15]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[2697, 6332, 2691, 4196], [2697, 6332, 2691, 503], [2697, 4423, 2691, 9609], [804, 7174, 2102, 7610, 6147], [804, 7174, 2102, 7610, 8947], [8081, 2697, 2669, 2691, 9906], [6649, 356, 1327, 7610]]


## WORD EMBEDDING REPRESENTAION


In [19]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [20]:
import numpy as np

In [24]:
sent_length = 8
embedded_docs=pad_sequences(onehot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2697 6332 2691 4196]
 [   0    0    0    0 2697 6332 2691  503]
 [   0    0    0    0 2697 4423 2691 9609]
 [   0    0    0  804 7174 2102 7610 6147]
 [   0    0    0  804 7174 2102 7610 8947]
 [   0    0    0 8081 2697 2669 2691 9906]
 [   0    0    0    0 6649  356 1327 7610]]


In [26]:
dim=15

In [29]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [31]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 160ms/step
[[[-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809
   -0.03465438 -0.02920153  0.00101965 -0.01755593  0.02322531]
  [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809
   -0.03465438 -0.02920153  0.00101965 -0.01755593  0.02322531]
  [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809
   -0.03465438 -0.02920153  0.00101965 -0.01755593  0.02322531]
  [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809
   -0.03465438 -0.02920153  0.00101965 -0.01755593  0.02322531]
  [ 0.04789427  0.01286323 -0.00453049  0.01984474  0.00331845
   -0.04894332  0.01499379  0.03423959  0.03732384  0.02750738]
  [-0.00431477  0.01344141 -0.0194838   0.0107044   0.01075184
   -0.0343985  -0.02329302 -0.01010773  0.0200052  -0.00679574]
  [-0.01076455  0.04320312 -0.04435952  0.0028639  -0.04860676
    0.00136309  0.00409069 -0.02553356 -0.02135067 -0.04706698]
  [ 0.00196049 -0.00718192 -0.01560252  0.01235472 -0.0230

In [32]:
embedded_docs[1]

array([   0,    0,    0,    0, 2697, 6332, 2691,  503])

In [33]:
print(model.predict(embedded_docs)[1])

1/1 [==============================] - 0s 48ms/step
[[-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809 -0.03465438
  -0.02920153  0.00101965 -0.01755593  0.02322531]
 [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809 -0.03465438
  -0.02920153  0.00101965 -0.01755593  0.02322531]
 [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809 -0.03465438
  -0.02920153  0.00101965 -0.01755593  0.02322531]
 [-0.00572872  0.03032602  0.0099748  -0.0091138   0.03186809 -0.03465438
  -0.02920153  0.00101965 -0.01755593  0.02322531]
 [ 0.04789427  0.01286323 -0.00453049  0.01984474  0.00331845 -0.04894332
   0.01499379  0.03423959  0.03732384  0.02750738]
 [-0.00431477  0.01344141 -0.0194838   0.0107044   0.01075184 -0.0343985
  -0.02329302 -0.01010773  0.0200052  -0.00679574]
 [-0.01076455  0.04320312 -0.04435952  0.0028639  -0.04860676  0.00136309
   0.00409069 -0.02553356 -0.02135067 -0.04706698]
 [ 0.01110777 -0.03392942 -0.0051054  -0.00335224  0.02199903  0.00697093
